pull_request_rules:
  - name: Automatic rebase, CI and merge
    conditions:
      - "-merged"
      - "#approved-reviews-by>=1"
      - base=main
      - label=AUTOMERGE-REQUESTED
      - status-success=Docs
      - status-success=Lint
      - status-success=Python (3.6, macos-latest)
      - status-success=Python (3.8, macos-latest)
      - status-success=Python (3.6, ubuntu-latest)
      - status-success=Python (3.8, ubuntu-latest)
      - status-success=Python (3.6, windows-latest)
      - status-success=Python (3.8, windows-latest)
      - "status-success=ci/circleci: build"
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: merge
        bot_account: AdminBot-tskit

  - name: Remove label after merge
    conditions:
      - merged
      - label=AUTOMERGE-REQUESTED
    actions:
      label:
        remove:
          - AUTOMERGE-REQUESTED