# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tsinfer manual
author: Tskit Developers
copyright: "2018"
only_build_toc_files: true
logo: tsinfer_logo.svg
favicon: favicon.ico

execute:
  execute_notebooks: cache

launch_buttons:
  binderhub_url: ""

repository:
  url: https://github.com/tskit-dev/tsinfer
  branch: main
  path_to_book: docs

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

sphinx:
    extra_extensions:
    - sphinx_copybutton
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.todo
    - sphinx.ext.viewcode
    - sphinx.ext.intersphinx
    - sphinx_issues
    - sphinxarg.ext
    - IPython.sphinxext.ipython_console_highlighting

    config:
      html_theme: sphinx_book_theme
      html_theme_options:
        pygments_dark_style: monokai
        navigation_with_keys: false
        logo:
          text: "Version __TSINFER_VERSION__"
      pygments_style: monokai
      myst_enable_extensions:
      - colon_fence
      - deflist
      issues_github_path: tskit-dev/tsinfer
      todo_include_todos: true
      intersphinx_mapping:
        python: ["https://docs.python.org/3/", null]
        tskit: ["https://tskit.dev/tskit/docs/stable", null]
        msprime: ["https://tskit.dev/msprime/docs/stable", null]
        tutorials: ["https://tskit.dev/tutorials/", null]
        numpy: ["https://numpy.org/doc/stable/", null]
        numcodecs: ["https://numcodecs.readthedocs.io/en/stable/", null]
        zarr: ["https://zarr.readthedocs.io/en/stable/", null]
      nitpicky: true

      autodoc_member_order: bysource

      # Without this option, autodoc tries to put links for all return types
      # in terms of the fully-qualified classnames
      # (e.g. msprime.demography.Demography) which we don't want, and also
      # leads to broken links and nitpick failures. So, until we tackle
      # typehints fully, this is the simplest approach.
      autodoc_typehints: none

      # Note we have to use the regex version here because of
      # https://github.com/sphinx-doc/sphinx/issues/9748
      nitpick_ignore_regex: [
        [ "py:class", "arraylike" ],
        [ "py:class", "array_like" ],
        [ "py:class", "array" ],
        [ "py:class", "dtype=float64" ],
        [ "py:class", "dtype=uint32" ],
        [ "py:class", "dtype=int8" ],
        [ "py:class", "iter" ],
      ]
