name: Docs
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  merge_group:
# Disabled until major code changes completed.
# jobs:
#   Docs:
#     uses: tskit-dev/.github/.github/workflows/docs.yml@v15
