name: Docs
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  merge_group:
jobs:
  Docs:
    uses: tskit-dev/.github/.github/workflows/docs-build-template.yml@v1
    with:
      additional-setup: sudo apt-get install -y tabix
      make-command: make all
