name: Docs
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  merge_group:

jobs:
  Docs:
    #Disabled until major code changes completed.
    # uses: tskit-dev/.github/.github/workflows/docs.yml@v15

    # Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Docs broken, fix when code is ready!"
