name: Tests

on:
  pull_request:
  push:
    branches: [main, test]
  merge_group:

jobs:

  packaging:
    name: Python packaging
    uses: tskit-dev/.github/.github/workflows/python-packaging.yml@v15
    with:
      cli-test-cmd: tsinfer --help

  test-c:
    name: C tests
    uses: tskit-dev/.github/.github/workflows/c-tests.yml@v15
    with:
      library-directory: lib
    secrets: inherit

  test-python-c:
    name: Python-C tests
    uses: tskit-dev/.github/.github/workflows/python-c-tests.yml@v15
    secrets: inherit

  test:
    name: Python
    uses: tskit-dev/.github/.github/workflows/python-tests.yml@v15
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python }}
      coverage-directory: tsinfer
    secrets: inherit
    strategy:
      matrix:
        python: [ 3.11, 3.13 ]
        os:  [ macos-latest, ubuntu-24.04, windows-latest ]
